# Generated by Django 5.2.17 on 2026-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="county",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
