# Generated by Django 5.2.17 on 2026-09-19 12:30

import cloudinary.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_galleryimage_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="video_url",
            field=models.URLField(
                blank=True, default="", validators=[core.validators.validate_video_url]
            ),
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "gallery_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.galleryimage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
