# Generated by Django 5.2.17 on 2026-09-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_backfill_gallery_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryimage",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="county",
        ),
        migrations.RemoveField(
            model_name="galleryimage",
            name="video_url",
        ),
    ]
