# Generated by Django 5.2.17 on 2026-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_remove_galleryimage_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("missions", "Missions"),
                    ("people", "People"),
                    ("places", "Places"),
                    ("stories", "Stories"),
                    ("documentaries", "Documentaries"),
                ],
                default="stories",
                max_length=20,
            ),
        ),
    ]
