# Generated by Django 5.2.17 on 2026-10-03 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_galleryimage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
