# Generated by Django 5.2.17 on 2026-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="involvement_interest",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prayer", "Prayer"),
                    ("field", "Field"),
                    ("media", "Media"),
                    ("partnership", "Partnership"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
