# Generated by Django 5.2.17 on 2026-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="county",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mission",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
