# Generated by Django 5.2.17 on 2026-09-19 12:30

import cloudinary.models
import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_mission_county_mission_end_date_mission_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={"ordering": ["-publish_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="mission",
            name="article",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mission",
            name="publish_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="mission",
            name="video_url",
            field=models.URLField(
                blank=True, default="", validators=[core.validators.validate_video_url]
            ),
        ),
        migrations.CreateModel(
            name="MissionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
